twig:
  default_path: '%kernel.project_dir%/templates'
    form_theme: [ 'bootstrap_5_horizontal_layout.html.twig', '@VichUploader/Form/fields.html.twig' ]
when@test:
    twig:
        strict_variables: true
