<?php

namespace App\Controller\Admin\Product;

use App\Controller\Admin\AbstractAttributableEntityController;
use App\Entity\Campaign\CampaignCategory;
use App\Entity\Product\Product;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext;

class ProductEntityController extends AbstractAttributableEntityController
{
    public static function getEntityFqcn(): string
    {
        return Product::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return parent::configureCrud($crud)->setPaginatorPageSize(50);
    }

    public function index(AdminContext $context)
    {
//        $meta = $this->getEntityManager()->getClassMetadata(ProductCategory::class);
//        dump($meta);
//        die;
        return parent::index($context); // TODO: Change the autogenerated stub
    }
}
