# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale : en
    web_base_path : '%kernel.project_dir%/public'
    upload_base_path : 'uploads'
    upload_image_path : 'uploads/images'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # make classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Bundles\Attribute\EventListener\AttributableEntityListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    app.attribute.nested:
        class: App\Bundles\Attribute\Manager\AttributeManagerNested

    app.attribute.parent_child:
        class: App\Bundles\Attribute\Manager\AttributeManagerParentChild

    app.attribute.database:
        class: App\Bundles\Attribute\Manager\AttributeManagerDatabase

    # all must be equal!!!
    App\Bundles\Attribute\AttributeManagerInterface: '@app.attribute.database'
    App\Bundles\Attribute\AttributeEntityManagerInterface: '@app.attribute.database'
    App\Bundles\Attribute\AttributeValueManagerInterface: '@app.attribute.database'